### ISSUE TITLE
Duplicate model definition when object property is nullable

### ISSUE THREAD

**Issue by florianajir** [nelmio/NelmioApiDocBundle#1333]
When I declare an object field as nullable (for serializer) this way

```
class MyObject
{
    /**
     * @var City|null
     */
    private $city;
   
    // ....
}
```

In swagger_ui, two blocs are generated (City and City2)

I think this is a bug

**Comment by epoplive** [comment]
I am having a similar issue, where most of my models are defined in the docs 2+ times.  I'm not sure what the fix is.

**Comment by florianajir** [comment]
This is due to PropertyInfo symfony component,

This is how I fixed it:

```
    /**
     * @var City|null
     * @SWG\Property(
     *     ref=@Model(type=City::class)
     * )
     */
    private $city;
```

This is explicitly telling to swagger the type instead of getting it from PropertyInfo.

**Comment by epoplive** [comment]
@florianajir thanks, that looks to be it.  Unfortunately figuring out where some of these duplicates are coming from this difficult as app and models are pretty significant in size.  Do you know if it's possible to find out what model the definition is coming from?

**Comment by florianajir** [comment]
@epoplive 

I forget :)

```
use Nelmio\ApiDocBundle\Annotation\Model;
use Swagger\Annotations as SWG;
```

**Comment by epoplive** [comment]
I'm still having issues with this.  I believe I have documented the model where it's used everywhere I can, I've even made sure to use the same serializer group definition everywhere, but still getting a duplicated model with a name like model2.

**Comment by GuilhemN** [comment]
Fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/1391, thanks for the report!
