### ISSUE TITLE
Error trying to convert from 2.x to 3.x running SwaggerDocblockConvertCommand.php

### ISSUE THREAD

**Issue by wraycode** [nelmio/NelmioApiDocBundle#1350]
Does anybody know how to resolve this error I'm trying to upgrade and everything is broken now, any help greatly appreciated

ERROR     [console] Error thrown while running command "api:doc:convert". Message: "You have requested a non-existent service "nelmio_api_doc.extractor.api_doc_extractor"." ["exception" => Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException { …},"command" => "api:doc:convert","message" => "You have requested a non-existent service "nelmio_api_doc.extractor.api_doc_extractor"."] []

In Container.php line 348:
                                                                                           
  You have requested a non-existent service "nelmio_api_doc.extractor.api_doc_extractor".  
                                                                                           

api:doc:convert [--views [VIEWS]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by wraycode** [comment]
was trying to upgrade to symfony 3.4 this is turning into a composer dependency nightmare

**Comment by wraycode** [comment]
this was my compser.json require 

    "require": {
        "php": ">=5.5.9",
        "components/font-awesome": "^4.7",
        "doctrine/annotations": "^1.4",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.3",
        "doctrine/doctrine-migrations-bundle": "^1.0",
        "doctrine/orm": "^2.5",
        "friendsofsymfony/rest-bundle": "~2.0",
        "guzzlehttp/guzzle": "~6.2",
        "guzzlehttp/psr7": "1.3",
        "jms/serializer-bundle": "^1.0",
        "leaseweb/memcache-bundle": "*",
        "lexik/jwt-authentication-bundle": "^2.4",
        "nategood/httpful": "*",
        "nelmio/api-doc-bundle": "2.0.*",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "symfony/cache": "3.2.*",
        "symfony/dependency-injection": "3.2.*",
        "symfony/monolog-bundle": "^3.0.2",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/symfony": "3.2.*",
        "twbs/bootstrap": "~3.3",
        "twig/twig": "^1.0||^2.0",
        "zircote/swagger-php": "^2.0"
    },

i'm now having to downgrade symfony in order to upgrade my Nelmio is this correct very frustrating

**Comment by wraycode** [comment]
with current configuration below composer runs but my swagger does not work
    "require": {
        "php": ">=5.5.9",
        "components/font-awesome": "^4.7",
        "doctrine/annotations": "^1.4",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.3",
        "doctrine/doctrine-migrations-bundle": "^1.0",
        "doctrine/orm": "^2.5",
        "friendsofsymfony/rest-bundle": "~2.0",
        "guzzlehttp/guzzle": "~6.2",
        "guzzlehttp/psr7": "1.3",
        "jms/serializer-bundle": "^1.0",
        "leaseweb/memcache-bundle": "*",
        "lexik/jwt-authentication-bundle": "^2.4",
        "nategood/httpful": "*",
        "nelmio/api-doc-bundle": "dev-master",
        "sensio/framework-extra-bundle": "^3.0.2",
        "symfony/cache": "3.4.*",
        "symfony/dependency-injection": "3.4.*",
        "symfony/monolog-bundle": "^3.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/symfony": "3.4.*",
        "twbs/bootstrap": "~3.3",
        "twig/twig": "^1.0||^2.0",
        "zircote/swagger-php": "^2.0"
    },
    "require-dev": {
        "doctrine/doctrine-fixtures-bundle": "^2.3",
        "nelmio/alice": "^2.3",
        "sensio/generator-bundle": "^3.0",
        "symfony/maker-bundle": "^1.5",
        "symfony/phpunit-bridge": "^3.0"
    },


SWAGGER
    /**
     * @Security("is_granted('IS_AUTHENTICATED_FULLY')")
     *
     * @Route("/api/shipping/product", name="get_shipping_product", methods={"GET"})
     *
     *
     *     
     * @SWG\Get(
     *
     *     produces={"application/json"},
     *     consumes={"application/json"},
     *     tags={"Shipping Product"}
     *     @SWG\Parameter(
     *         name="Authorization",
     *         in="header",
     *         required=true,
     *         type="string",
     *         default="Bearer TOKEN",
     *         description="Authorization"
     *     ),          
     *     @SWG\Parameter(
     *         name="productNumber",
     *         in="query",
     *         required=true,
     *         type="integer",
     *         default=2401,
     *         description="Product Number"
     *     ),       
     *     @SWG\Response(
     *         response=200,
     *         description="Returns base64 image",
     *     ),
     *     @SWG\Response(
     *         response=401,
     *         description="Expired JWT Token | JWT Token not found | Invalid JWT Token",
     *     ) 
     *
     *
     * )
     *
     */

I get a error
Using the annotation \"Swagger\\Annotations\\Definition\" as a root annotation in \"ApiBundle\\Controller\\ApiShippingChargesProduct::getChargeLargePackage()\" is not allowed.

any help greatly appreciated

**Comment by wraycode** [comment]
I also get this error when tryinng to clear cache

 // Clearing the cache for the dev environment with debug true                                                      


In FileLoader.php line 168:
                                                                                                                   
  User Notice: Unexpected field "produces" for @SWG\Definition(), expecting "definition", "ref", "title", "descri  
  ption", "maxProperties", "minProperties", "required", "properties", "type", "format", "items", "collectionForma  
  t", "default", "maximum", "exclusiveMaximum", "minimum", "exclusiveMinimum", "maxLength", "minLength", "pattern  
  ", "maxItems", "minItems", "uniqueItems", "enum", "multipleOf", "discriminator", "readOnly", "xml", "externalDo  
  cs", "example", "allOf", "additionalProperties", "x" in \Doctrine\Common\Annotations\DocParser->Annotation() in  
   /var/www/html/cg-open-api/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 82  
  0 in /var/www/html/cg-open-api/src/ApiBundle/Controller/ (which is being imported from "/var/www/html/cg-open-a  
  pi/app/config/routing.yml"). Make sure annotations are installed and enabled.                                    
                                                                                                                   

In Logger.php line 38:
                                                                                                                   
  User Notice: Unexpected field "produces" for @SWG\Definition(), expecting "definition", "ref", "title", "descri  
  ption", "maxProperties", "minProperties", "required", "properties", "type", "format", "items", "collectionForma  
  t", "default", "maximum", "exclusiveMaximum", "minimum", "exclusiveMinimum", "maxLength", "minLength", "pattern  
  ", "maxItems", "minItems", "uniqueItems", "enum", "multipleOf", "discriminator", "readOnly", "xml", "externalDo  
  cs", "example", "allOf", "additionalProperties", "x" in \Doctrine\Common\Annotations\DocParser->Annotation() in  
   /var/www/html/cg-open-api/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 82  
  0                                                                                                                
                                                                                                                   

cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by GuilhemN** [comment]
The command must be run on 2.x and only afterwards you should update your dependencies.

**Comment by wraycode** [comment]
ended up just copying over my lock file from production will deal with these upgrade problems later, I was already higher than 2.x

**Comment by MonaGolkarAtGitHub** [comment]
ok, so I checked out a new branch out of master, got the version 2 up again, now I have issue understanding the guide. What does `src/AppBundle/Command/SwaggerDocblockConvertCommand.php` is referring to? 

When I put it in the src of my project (which does not have the command folder in the root, it is inside one of our bundle folders) I get the CommandNotFoundException thrown

When I put it in the `vendor/composer/../nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Command/` it throws another error:

**Comment by MonaGolkarAtGitHub** [comment]
ok, I fixed it up in a weird way. I hope the resulted changed files are reliable to be transferred to my updated version branch! 

so I found the [older version](https://github.com/nelmio/NelmioApiDocBundle/blob/4990eb9152fd6ed94b231d46fd442840eff107a2/Annotation/ApiDoc.php) of `ApiDoc.php` in the repository with all the missing methods in it. Copied it over to the `/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Annotation\ApiDoc.php` and tried the command again, which worked without any error and I see changes in the files.

said these just in case someone else has the same issues. Since that guide wasn't really explanatory at least for me! a bundle update shouldn't be this painful!

**Comment by probfacile** [comment]
"You have requested a non-existent service "nelmio_api_doc.extractor.api_doc_extractor"."
this means you have never enabled the bundle:
https://symfony.com/doc/2.x/bundles/NelmioApiDocBundle/index.html  step 2.
after this the comman will work, but it's still not working for me for other errors
